// Generator for probe_outlookcom-pane-px-rows-2026-09-29.mjml (run from the
// repo root: node src/probes/probe_outlookcom-pane-px-rows-2026-09-29.gen.mjs).
// It copies each block's region out of src/main.mjml so the probe can never
// drift from what ships, and emits an A/B pair per block:
//   A = the block as shipped (MJML's px pins under min-width:600px);
//   B = the same block with its fixed-px columns restated as the percentages
//       of their row, rounded DOWN to one decimal and scoped to that row —
//       the idiom styles.css uses for the video bands (guide §6e).
// Re-run it after a catalog change, then rebuild.
import { readFileSync, writeFileSync } from 'node:fs';

const OUT = 'src/probes/probe_outlookcom-pane-px-rows-2026-09-29.mjml';
const main = readFileSync('src/main.mjml', 'utf8');

const BLOCKS = [
  // name, px widths of the row that fills the frame (sum = frame)
  ['CTA Hero (w/ background image)', [16, 240, 328, 16]],
  ['CTA Hero (w/ heading)', [16, 240, 328, 16]],
  ['Photo Banner (w/ CTA)', [16, 568, 16]],
  ['Story Card (image right, left aligned)', [240, 328]],
  ['Icon Row', [120, 448]],
  ['Podcast Streaming Block', [412, 78, 78]],
  ['Signature Card (photo)', [112, 456]],
  ['Progress Meter Block', [16, 568, 16]],
];
const CONTROL = 'Video Block'; // already carries the percentage restatement

const region = (name) => {
  const a = main.indexOf(`<!-- START: ${name} -->`);
  const b = main.indexOf(`<!-- END: ${name} -->`);
  if (a < 0 || b < 0) throw new Error(`block not found: ${name}`);
  return main.slice(a, b + `<!-- END: ${name} -->`.length);
};
// Probe copies must not look like catalog blocks to any tool that scans for
// START/END markers. Only the markers are renamed: stripping other comments
// here once ate `<!--[if !mso]><!-->` (its `<!-->` reads as a comment
// opener) and the markup after it; prose comments are harmless, the build's
// compaction drops them from _live.
const detag = (s, label) => s.replace(/<!-- (START|END): [^>]*-->/g, `<!-- probe copy: ${label} -->`);

const scope = (s, cls) => s.replace(/<mj-section\b([^>]*?)css-class="([^"]*)"/g, `<mj-section$1css-class="$2 ${cls}"`);

const pct = (px, frame) => Math.floor((px / frame) * 1000) / 10;

const bar = (text, color) => `
    <mj-section css-class="block" background-color="${color}" padding="8px 16px">
      <mj-column><mj-text color="#362229" padding="0"><p style="font-weight:700;margin:0;">${text}</p></mj-text></mj-column>
    </mj-section>`;

const rules = [];
const rows = [];
BLOCKS.forEach(([name, widths], i) => {
  const n = i + 1;
  const frame = widths.reduce((a, b) => a + b, 0);
  const cls = `pane-b${n}`;
  for (const w of [...new Set(widths)]) {
    rules.push(`      .${cls} .mj-column-px-${w} { width: ${pct(w, frame)}% !important; }`);
  }
  const src = region(name);
  rows.push(bar(`A${n} · ${name} — as shipped (px pins)`, '#CEE4C5'));
  rows.push(detag(src, `A${n} ${name}`));
  rows.push(bar(`B${n} · ${name} — percentages ${[...new Set(widths)].map((w) => `${w}→${pct(w, frame)}%`).join(', ')}`, '#5DD8D8'));
  rows.push(scope(detag(src, `B${n} ${name}`), cls));
});
rows.push(bar(`C · ${CONTROL} — control (video-band restatement already shipped)`, '#F7931E'));
rows.push(detag(region(CONTROL), `C ${CONTROL}`));

const headEnd = main.indexOf('</mj-head>');
const head = main
  .slice(main.indexOf('<mj-head>'), headEnd)
  .replace('<mj-include path="./styles.css" type="css" />', '<mj-include path="../styles.css" type="css" />');

const header = `<!--
      PROBE — Outlook.com reading pane vs fixed-px rows (2026-09-29).
      GENERATED by probe_outlookcom-pane-px-rows-2026-09-29.gen.mjs from
      src/main.mjml; edit the generator, never this file.

      Guide §6e (desktop half, EoA OawK4B…, 2026-09-29): MJML pins every px
      column with width:Npx !important inside @media (min-width:600px), and
      Outlook.com evaluates that against the WINDOW, not its ~538px reading
      pane, so a row wider than the pane can wrap. The video bands got a
      scoped percentage restatement; nothing else did.

      == CLAIMS
        P1  In Outlook.com (light and dark, normal window) the A rows WRAP:
            a fixed-px column drops below its neighbour (heroes: the 328 text
            column under the logo; pairs: the second column under the first).
        P2  The B rows do NOT wrap there: the scoped percentages hold the row
            on one line at the pane's width.
        P3  B rows match A rows in every OTHER client at 600px to within 1px
            (the restatement is MJML's own inline percentage, rounded DOWN so
            the row can never overfill), and exactly on phones (the rules
            sit under min-width:600px).
        P4  (control) C, the shipped Video Block, does not wrap in Outlook.com.
      Read Outlook.com light first, then dark, then every other client for P3.

      == ROWS  Moss bar = A (as shipped), Sky bar = B (restated), Sun bar = C.
${BLOCKS.map(([n], i) => `        ${i + 1}  ${n}`).join('\n')}

      PRE-CHECK (Chromium, 2026-09-29 — a SIMULATION, not a measurement): a
      1200px window (so the min-width:600px pins apply) with the email in a
      538px container. Every A row wrapped (heroes: text column under the
      logo; pairs stacked), every B row held one line, C held. At a 600px
      viewport B matched A within 1px. Only a real Outlook.com render can
      settle P1-P4.

      ROUND 1 (2026-09-29, sent through EN, EoA 69P1Kcg…, 19 clients;
      Outlook 2016/2019 at 120 DPI not yet rendered, Outlook 2021 dark a
      near-empty capture).
        P1, P2 NOT MEASURABLE this round: BOTH Outlook.com captures (light
          and dark) got a ~600px reading pane (email card 602px at a 1440
          window), where the px pins fit, so nothing could wrap. Every A and
          B row and C sat on one line in both. EoA's pane width varies per
          capture: the video probe's round 1 light was ~538 (wrapped) and its
          dark ~600 (fine). A narrow-pane capture is still needed.
        P3 PASSES: Outlook 2021 (Word), Gmail web, Apple Mail and iPhone
          render A and B the same (Word reads the MSO tables; phones sit
          under the mobile pins).
        P4 PASSES, weakly: C held one line, but in a pane that could not
          make it wrap.
        Also seen: dark mode repaints the probe's label bars black (they
          carry .block); the labels stay readable.

      CLOSED 2026-09-29, NOT REPRODUCIBLE (user decision): EoA's Outlook.com
      capture offers only the ~600px pane (the user's account of the
      service), so P1/P2 cannot be measured there; this contradicts the
      video probe's recorded ~538px readings, which may have misjudged the
      pane. No fix shipped: the restatement would spend ~250 of the 257
      head-CSS bytes left for a wrap never directly observed. Re-open by
      sending this to a real Outlook.com mailbox and narrowing the window
      below a 600px reading pane.

      VERDICTS: P3, P4 pass; P1, P2 not reproducible in EoA. Archived.
    -->`;

const out = `<mjml lang="en">
  <mj-head>
    ${header}
${head.slice('<mj-head>'.length)}    <mj-style>
      @media only screen and (min-width:600px) {
${rules.join('\n')}
      }
    </mj-style>
  </mj-head>
  <mj-body css-class="email-body" background-color="#ffffff">
${rows.join('\n')}
  </mj-body>
</mjml>
`;
writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${BLOCKS.length} A/B pairs + control, ${rules.length} restatement rules`);
